# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Compile

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
      steps:
      - uses: actions/checkout@v2
      - run: npm run i && npm run build
      # Commit the build files to the repository
      - name: Commit build files
        uses: actions/checkout@v2
        with:
          path: "."
          message: "Build files"
